In [1]:
#0D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [5]:
#1D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#2D array
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [7]:
#3D array
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [8]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


In [9]:
#array indexing
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])


2


In [10]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print('2nd element on 1st Row', arr[0,1])

2nd element on 1st Row 2


In [12]:
#slice
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:5])

[1 2 3 4 5]


In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:])



[1 2 3 4 5 6 7 8 9]


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])



[5 6 7 8 9]


In [16]:
#negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5:2])

[2 4]


In [19]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [21]:
#slicing 2D arrays
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr[1,1:4])

[2 3 4]


In [22]:
#numpy array 3x3
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
import numpy as np
arr = np.array([])
print(arr)

In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


In [25]:
import numpy as np
np.eye(3)
print(arr)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
